/**
 * L-Corparation - Accessories Data
 * VinFast vehicle accessories data
 */

const accessoriesData = [
    // Phụ kiện dành riêng cho Xe máy điện (E-Scooter Specific Accessories) - CHUYỂN LÊN ĐẦU ĐỂ DỄ THẤY
    {
        id: 'sct-001',
        name: 'Mũ Bảo Hiểm Siêu Nhẹ An Toàn',
        category: 'scooter_acc',
        categoryName: 'Phụ kiện Xe máy điện',
        img: 'https://shop.vinfastauto.com/on/demandware.static/-/Sites-vinfast_vn_master/default/dwb720560c/images/Accessory/UltraLightSafetyHelmet/MBH%20-%20Trang%20-%204.png',
        price: 850000,
        price_old: 1100000,
        discount: 23,
        isNew: true,
        vehicle: 'all',
        vehicleType: 'scooter',
        vehicleName: 'Tất cả xe máy điện'
    },
    {
        id: 'sct-002',
        name: 'Áo Mưa Cánh Dơi Một Mũ',
        category: 'scooter_acc',
        categoryName: 'Phụ kiện Xe máy điện',
        img: 'https://shop.vinfastauto.com/on/demandware.static/-/Sites-vinfast_vn_master/default/dwa6503322/images/Accessory/ACS40000013/AM1D-%202.png',
        price: 150000,
        price_old: 220000,
        discount: 32,
        vehicle: 'all',
        vehicleType: 'scooter',
        vehicleName: 'Tất cả xe máy điện'
    },
    {
        id: 'sct-003',
        name: 'Áo Mưa Cánh Dơi Hai Mũ',
        category: 'scooter_acc',
        categoryName: 'Phụ kiện Xe máy điện',
        img: 'https://shop.vinfastauto.com/on/demandware.static/-/Sites-vinfast_vn_master/default/dw0dd2f302/images/Accessory/ACS40000014/AM2D%20-%202.png',
        price: 120000,
        price_old: 180000,
        discount: 33,
        vehicle: 'all',
        vehicleType: 'scooter',
        vehicleName: 'Tất cả xe máy điện'
    },
    {
        id: 'sct-004',
        name: 'Bộ sạc xe điện đảm bảo cung cấp năng lượng cho hoạt động ',
        category: 'scooter_acc',
        categoryName: 'Phụ kiện Xe máy điện',
        img: 'https://static-cms-prod.vinfastauto.com/cuc-sac-xe-dap-dien-bi-hu_1721190272.jpg',
        price: 350000,
        price_old: 500000,
        discount: 30,
        vehicle: 'all',
        vehicleType: 'scooter',
        vehicleName: 'Tất cả xe máy điện'
    },
    {
        id: 'sct-005',
        name: 'Bộ Phụ Kiện Danh cho Xe Điện VinFast Vero X',
        category: 'scooter_acc',
        categoryName: 'Phụ kiện Xe máy điện',
        img: 'https://cf.shopee.vn/file/vn-11134207-820l4-mgysh58rvevd66',
        price: 280000,
        price_old: 380000,
        discount: 26,
        isNew: true,
        vehicle: 'all',
        vehicleType: 'scooter',
        vehicleName: 'Tất cả xe máy điện'
    },

    // Phụ kiện bảo hộ (Safety Accessories)
    // Tấm che bảo vệ pin xe cao áp (High Voltage Battery Covers)
    {
        id: 'mod-001',
        name: 'Camera Lùi VF 3',
        category: 'car_acc',
        categoryName: 'Phụ kiện Ô tô điện',
        img: 'https://shop.vinfastauto.com/on/demandware.static/-/Sites-vinfast_vn_master/default/dwa83d9527/images/Accessory/EEP73090003AB/EEP73090003AB.png',
        price: 3500000,
        price_old: 4200000,
        discount: 17,
        isNew: true,
        vehicle: 'vf3',
        vehicleType: 'car',
        vehicleName: 'VF 3'
    },
    {
        id: 'mod-002',
        name: 'Tấm Che Nắng Cửa VinFast VF 3',
        category: 'car_acc',
        categoryName: 'Phụ kiện Ô tô điện',
        img: 'https://shop.vinfastauto.com/on/demandware.static/-/Sites-vinfast_vn_master/default/dwacbc61eb/images/Accessory/ACS10000142/CN%20-VF3%20-%2001.png',
        price: 4200000,
        price_old: 5000000,
        discount: 16,
        vehicle: 'vf3',
        vehicleType: 'car',
        vehicleName: 'VF 3'
    },
    {
        id: 'mod-003',
        name: 'Ốp Lưng Ghế Sau VF 3',
        category: 'car_acc',
        categoryName: 'Phụ kiện Ô tô điện',
        img: 'https://shop.vinfastauto.com/on/demandware.static/-/Sites-vinfast_vn_master/default/dw5426f40f/images/Accessory/ACS10000145/OLVF3%20-%201.png',
        price: 4800000,
        price_old: 5800000,
        discount: 17,
        vehicle: 'vf3',
        vehicleType: 'car',
        vehicleName: 'VF 3'
    },
    {
        id: 'mod-004',
        name: 'VF 5 Tấm Che Pin Cao Áp',
        category: 'car_acc',
        categoryName: 'Phụ kiện Ô tô điện',
        img: 'https://shop.vinfastauto.com/on/demandware.static/-/Sites-vinfast_vn_master/default/dw3a4f3add/images/Accessory/EEP73111000AA/1.png',
        price: 3900000,
        price_old: 4800000,
        discount: 19,
        vehicle: 'vf5',
        vehicleType: 'car',
        vehicleName: 'VF 5'
    },
    {
        id: 'mod-005',
        name: 'Thảm Cốp 3D VF 5',
        category: 'car_acc',
        categoryName: 'Phụ kiện Ô tô điện',
        img: 'https://shop.vinfastauto.com/on/demandware.static/-/Sites-vinfast_vn_master/default/dweae9bb85/images/Accessory/ACS10000008/1.png',
        price: 5500000,
        price_old: 6800000,
        discount: 19,
        vehicle: 'vf5',
        vehicleType: 'car',
        vehicleName: 'VF 5'
    },
    {
        id: 'mod-006',
        name: 'Thảm Sàn Nhựa 3D VF 6',
        category: 'car_acc',
        categoryName: 'Phụ kiện Ô tô điện',
        img: 'https://shop.vinfastauto.com/on/demandware.static/-/Sites-vinfast_vn_master/default/dwd5b08a38/images/Accessory/ACS10000035/1.png',
        price: 6500000,
        price_old: 8200000,
        discount: 21,
        vehicle: 'vf6',
        vehicleType: 'car',
        vehicleName: 'VF 6'
    },
    {
        id: 'mod-007',
        name: 'VF 9 Tấm Che Pin Cao Áp',
        category: 'car_acc',
        categoryName: 'Phụ kiện Ô tô điện',
        img: 'https://shop.vinfastauto.com/on/demandware.static/-/Sites-vinfast_vn_master/default/dwca9bd466/images/Accessory/EEP80001000/1.png',
        price: 7800000,
        price_old: 9500000,
        discount: 18,
        vehicle: 'vf9',
        vehicleType: 'car',
        vehicleName: 'VF 9'
    },
    {
        id: 'mod-008',
        name: 'Bọc Vô Lăng VF 3',
        category: 'car_acc',
        categoryName: 'Phụ kiện Ô tô điện',
        img: 'https://shop.vinfastauto.com/on/demandware.static/-/Sites-vinfast_vn_master/default/dw2dbbabb5/images/Accessory/VHC69012100AA/VHC69012100AA.png',
        price: 4900000,
        price_old: 6200000,
        discount: 21,
        vehicle: 'vf3',
        vehicleType: 'car',
        vehicleName: 'VF 3'
    },
    {
        id: 'mod-009',
        name: 'Thanh Ngang Giá Nóc VinFast VF 8',
        category: 'car_acc',
        categoryName: 'Phụ kiện Ô tô điện',
        img: 'https://shop.vinfastauto.com/on/demandware.static/-/Sites-vinfast_vn_master/default/dw214c8c9c/images/Accessory/ACS30000142/01.png',
        price: 7200000,
        price_old: 8800000,
        discount: 18,
        vehicle: 'vf8',
        vehicleType: 'car',
        vehicleName: 'VF 8'
    },
    {
        id: 'mod-010',
        name: 'Tấm Rèm Trần Panorama VinFast VF 9',
        category: 'car_acc',
        categoryName: 'Phụ kiện Ô tô điện',
        img: 'https://shop.vinfastauto.com/on/demandware.static/-/Sites-vinfast_vn_master/default/dwac8fd32c/images/Accessory/ACS10000018/1.png',
        price: 8000000,
        price_old: 11000000,
        discount: 27,
        vehicle: 'vf9',
        vehicleType: 'car',
        vehicleName: 'VF 9'
    },
    {
        id: 'mod-011',
        name: 'VF 7 Tấm Che Pin Cao Áp',
        category: 'car_acc',
        categoryName: 'Phụ kiện Ô tô điện',
        img: 'https://shop.vinfastauto.com/on/demandware.static/-/Sites-vinfast_vn_master/default/dw2aa5cf69/images/Accessory/EEP71061000/1.png',
        price: 8000000,
        price_old: 11000000,
        discount: 27,
        vehicle: 'vf9',
        vehicleType: 'car',
        vehicleName: 'VF 9'
    },
    {
        id: 'mod-012',
        name: 'Gói Dán Film Cách Nhiệt VinFast VF 8',
        category: 'car_acc',
        categoryName: 'Phụ kiện Ô tô điện',
        img: 'https://shop.vinfastauto.com/on/demandware.static/-/Sites-vinfast_vn_master/default/dw964130cb/images/Accessory/INSULATIONFILM/INSULATIONFILMVF8/1.png',
        price: 7200000,
        price_old: 8800000,
        discount: 18,
        vehicle: 'vf8',
        vehicleType: 'car',
        vehicleName: 'VF 8'
    },

   // Mô hình xe cao cấp (Premium Car Models)
    {
        id: 'mod-001',
        name: 'Mô Hình Xe VinFast VF 3',
        category: 'car_acc',
        categoryName: 'Phụ kiện Ô tô điện',
        img: 'https://shop.vinfastauto.com/on/demandware.static/-/Sites-vinfast_vn_master/default/dw79e030a9/images/Accessory/VINFASTVF3SCALECARMODELS/yellow01.png',
        price: 3500000,
        price_old: 4200000,
        discount: 17,
        isNew: true,
        vehicle: 'vf3',
        vehicleType: 'car',
        vehicleName: 'VF 3'
    },
    {
        id: 'bat-002',
        name: 'Mô Hình Xe VinFast VF 8',
        category: 'car_acc',
        categoryName: 'Phụ kiện Ô tô điện',
        img: 'https://shop.vinfastauto.com/on/demandware.static/-/Sites-vinfast_vn_master/default/dwea9ebcf1/images/Accessory/VINFASTSCALECARMODELS/ACS30000077/1.png',
        price: 3800000,
        price_old: 4500000,
        discount: 16,
        vehicle: 'vf6',
        vehicleType: 'car',
        vehicleName: 'VF 6'
    },
    {
        id: 'bat-003',
        name: 'Mô Hình Xe VinFast VF 9',
        category: 'car_acc',
        categoryName: 'Phụ kiện Ô tô điện',
        img: 'https://shop.vinfastauto.com/on/demandware.static/-/Sites-vinfast_vn_master/default/dwedcc5052/images/Accessory/VINFASTSCALECARMODELS/ACS30000074/1%20.png',
        price: 3600000,
        price_old: 4300000,
        discount: 16,
        vehicle: 'vfe34',
        vehicleType: 'car',
        vehicleName: 'VFe34'
    },
    {
        id: 'bat-004',
        name: 'Mô Hình Xe VinFast lux A2.0',
        category: 'car_acc',
        categoryName: 'Phụ kiện Ô tô điện',
        img: 'https://trummohinh.com/wp-content/uploads/2020/03/VINFAST-LUX-A2.0-SEDAN_01.jpg',
        price: 4200000,
        price_old: 5000000,
        discount: 16,
        isNew: true,
        vehicle: 'vf7',
        vehicleType: 'car',
        vehicleName: 'VF 7'
    },


    // Bộ sạc VinFast chính hãng (VinFast Official Chargers)
    {
        id: 'chg-001',
        name: 'Sạc Tại Nhà 3KW',
        category: 'car_acc',
        categoryName: 'Phụ kiện Ô tô điện',
        img: 'https://shop.vinfastauto.com/on/demandware.static/-/Sites-vinfast_vn_master/default/dw626dfae2/images/Accessory/EEP69072176AB/01.png',
        price: 8500000,
        price_old: 10500000,
        discount: 19,
        isNew: true,
        vehicle: 'all',
        vehicleType: 'all',
        vehicleName: 'Tất cả xe'
    },
    {
        id: 'chg-002',
        name: 'Bộ Sạc Treo Tường AC 11 kW',
        category: 'car_acc',
        categoryName: 'Phụ kiện Ô tô điện',
        img: 'https://shop.vinfastauto.com/on/demandware.static/-/Sites-vinfast_vn_master/default/dwf6965263/images/Accessory/EEP30000011/1.png',
        price: 12500000,
        price_old: 15000000,
        discount: 17,
        vehicle: 'all',
        vehicleType: 'all',
        vehicleName: 'Tất cả xe'
    },
    {
        id: 'chg-003',
        name: 'Bộ Sạc Di Động Ô Tô Điện 2.2 kW',
        category: 'car_acc',
        categoryName: 'Phụ kiện Ô tô điện',
        img: 'https://shop.vinfastauto.com/on/demandware.static/-/Sites-vinfast_vn_master/default/dw3060cd2a/images/Accessory/EEH20000204/1.png',
        price: 2800000,
        price_old: 3500000,
        discount: 20,
        vehicle: 'all',
        vehicleType: 'car',
        vehicleName: 'Tất cả xe máy điện'
    },
    {
        id: 'chg-004',
        name: 'Bộ Sạc Treo Tường AC 7,4 kW',
        category: 'car_acc',
        categoryName: 'Phụ kiện Ô tô điện',
        img: 'https://shop.vinfastauto.com/on/demandware.static/-/Sites-vinfast_vn_master/default/dwa0be0ad5/images/Accessory/CHG00009020/1.png',
        price: 25000000,
        price_old: 32000000,
        discount: 22,
        vehicle: 'all',
        vehicleType: 'car',
        vehicleName: 'Tất cả ô tô điện'
    },

    // Sản phẩm Lifestyle & Thời trang (Lifestyle & Fashion Products)
    {
        id: 'lfs-001',
        name: 'Mũ Lưỡi Trai Thêu Hoa VF 5',
        category: 'lifestyle',
        categoryName: 'Phong cách sống',
        img: 'https://shop.vinfastauto.com/on/demandware.static/-/Sites-vinfast_vn_master/default/dwa2be9db4/images/Accessory/VF5FLORALEMBROIDEREDCAP/Black.png',
        price: 250000,
        price_old: 350000,
        discount: 29,
        isNew: true,
        vehicle: 'all',
        vehicleType: 'all',
        vehicleName: 'Tất cả xe'
    },
    {
        id: 'lfs-002',
        name: 'Áo Phông VF 7 Đặc Biệt',
        category: 'lifestyle',
        categoryName: 'Phong cách sống',
        img: 'https://shop.vinfastauto.com/on/demandware.static/-/Sites-vinfast_vn_master/default/dw46439f38/images/Accessory/VF7SPECIALTSHIRT/Black/1.png',
        price: 450000,
        price_old: 650000,
        discount: 31,
        isNew: true,
        vehicle: 'all',
        vehicleType: 'all',
        vehicleName: 'Tất cả xe'
    },
    {
        id: 'lfs-003',
        name: 'Mũ Lưỡi Trai VF 7',
        category: 'lifestyle',
        categoryName: 'Phong cách sống',
        img: 'https://shop.vinfastauto.com/on/demandware.static/-/Sites-vinfast_vn_master/default/dwd0c6fdfe/images/Accessory/ACS30000104/1.png',
        price: 320000,
        price_old: 480000,
        discount: 33,
        vehicle: 'all',
        vehicleType: 'all',
        vehicleName: 'Tất cả xe'
    },
    {
        id: 'lfs-004',
        name: 'Lót Cốc Sơn Mài VinFast',
        category: 'lifestyle',
        categoryName: 'Phong cách sống',
        img: 'https://shop.vinfastauto.com/on/demandware.static/-/Sites-vinfast_vn_master/default/dwec6ae8a1/images/Accessory/ACS30000078/1.png',
        price: 380000,
        price_old: 550000,
        discount: 31,
        isNew: true,
        vehicle: 'all',
        vehicleType: 'all',
        vehicleName: 'Tất cả xe'
    },
    {
        id: 'lfs-005',
        name: 'Bình Giữ Nhiệt VF 7',
        category: 'lifestyle',
        categoryName: 'Phong cách sống',
        img: 'https://shop.vinfastauto.com/on/demandware.static/-/Sites-vinfast_vn_master/default/dw5f970a43/images/Accessory/THERMOSVINFASTVF7/White/1.png',
        price: 850000,
        price_old: 1250000,
        discount: 32,
        vehicle: 'all',
        vehicleType: 'all',
        vehicleName: 'Tất cả xe'
    },
    {
        id: 'lfs-006',
        name: 'Khăn Lụa Cao Cấp VinFast',
        category: 'lifestyle',
        categoryName: 'Phong cách sống',
        img: 'https://shop.vinfastauto.com/on/demandware.static/-/Sites-vinfast_vn_master/default/dw98542fed/images/Accessory/VINFASTSILKSCARF/Orange.png',
        price: 520000,
        price_old: 750000,
        discount: 31,
        isNew: true,
        vehicle: 'all',
        vehicleType: 'all',
        vehicleName: 'Tất cả xe'
    },
    {
        id: 'lfs-007',
        name: 'Thắt lưng da VinFast',
        category: 'lifestyle',
        categoryName: 'Phong cách sống',
        img: 'https://shop.vinfastauto.com/on/demandware.static/-/Sites-vinfast_vn_master/default/dw1cf7889e/images/Accessory/LEATHERBELTSVINFAST/4.png',
        price: 1200000,
        price_old: 1650000,
        discount: 27,
        vehicle: 'all',
        vehicleType: 'scooter',
        vehicleName: 'Tất cả xe máy điện'
    },
    {
        id: 'lfs-008',
        name: 'Bao Da Giấy Tờ Xe',
        category: 'lifestyle',
        categoryName: 'Phong cách sống',
        img: 'https://shop.vinfastauto.com/on/demandware.static/-/Sites-vinfast_vn_master/default/dw4b39849a/images/Accessory/REGISTRATIONLEATHERCASE/1.png',
        price: 450000,
        price_old: 650000,
        discount: 31,
        isNew: true,
        vehicle: 'all',
        vehicleType: 'all',
        vehicleName: 'Tất cả xe'
    },
    {
        id: 'lfs-009',
        name: 'Cốc Giữ Nhiệt Summit 470ml',
        category: 'lifestyle',
        categoryName: 'Phong cách sống',
        img: 'https://shop.vinfastauto.com/on/demandware.static/-/Sites-vinfast_vn_master/default/dw6126c00b/images/Accessory/THERMOSCUP470ML/01.png',
        price: 290000,
        price_old: 420000,
        discount: 31,
        isNew: true,
        vehicle: 'all',
        vehicleType: 'all',
        vehicleName: 'Tất cả xe'
    },
    {
        id: 'lfs-010',
        name: 'Áo Polo Nữ',
        category: 'lifestyle',
        categoryName: 'Phong cách sống',
        img: 'https://shop.vinfastauto.com/on/demandware.static/-/Sites-vinfast_vn_master/default/dw87a3fb7a/images/Accessory/FEMALEPOLOSHIRT/1.png',
        price: 150000,
        price_old: 250000,
        discount: 40,
        vehicle: 'all',
        vehicleType: 'all',
        vehicleName: 'Tất cả xe'
    },
    {
        id: 'lfs-011',
        name: 'Gối Cổ Chữ U',
        category: 'lifestyle',
        categoryName: 'Phong cách sống',
        img: 'https://shop.vinfastauto.com/on/demandware.static/-/Sites-vinfast_vn_master/default/dwa95926e6/images/Accessory/UNECKPILLOW/Gray/Gray.png',
        price: 150000,
        price_old: 250000,
        discount: 40,
        vehicle: 'all',
        vehicleType: 'all',
        vehicleName: 'Tất cả xe'
    },
    {
        id: 'lfs-012',
        name: 'Gối Da Tựa Đầu',
        category: 'lifestyle',
        categoryName: 'Phong cách sống',
        img: 'https://shop.vinfastauto.com/on/demandware.static/-/Sites-vinfast_vn_master/default/dwf40ffcea/images/Accessory/HEADLEATHERPILLOW/1.png',
        price: 150000,
        price_old: 250000,
        discount: 40,
        vehicle: 'all',
        vehicleType: 'all',
        vehicleName: 'Tất cả xe'
    }
];

// Category mapping for filtering
const accessoriesCategories = [
    { id: 'all', name: 'Tất cả sản phẩm', icon: 'fa-box', labelKey: 'accessories_cat_all' },
    { id: 'new', name: 'Sản phẩm mới', icon: 'fa-star', labelKey: 'accessories_cat_new' },
    { id: 'lifestyle', name: 'Phong cách sống', icon: 'fa-tshirt', labelKey: 'accessories_cat_lifestyle' },
    { id: 'car_acc', name: 'Phụ kiện Ô tô điện', icon: 'fa-car', labelKey: 'accessories_cat_car' },
    { id: 'scooter_acc', name: 'Phụ kiện Xe máy điện', icon: 'fa-motorcycle', labelKey: 'accessories_cat_scooter' }
];

// Format price to VND
function formatPrice(price) {
    return new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND' }).format(price);
}
